### PR TITLE
Create RomanToInt.py

### LINKED ISSUE #734: Roman To Integer | Math | Python
## **`Roman to Integer`** -

**Will  implement the conversion program** -

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Python

### PR DESCRIPTION
**Pull request by X0rD3v1L**
Roman To Integer conversion program using python.

### CODE REVIEW

**Review by hot9cups — CHANGES_REQUESTED** [review]
Lint your code with flake8. Your code has to pass the linting test in order to be merged.

**Comment by X0rD3v1L** [comment]
I am not able to lint properly. Can you suggest something?

**Comment by hot9cups** [comment]
@X0rD3v1L you can see what checks are failing [here](https://github.com/Py-Contributors/AlgorithmsAndDataStructure/pull/741/checks).

You should download [flake8](https://pypi.org/project/flake8/), and run it on your local machine.
You could install it in numerous ways, for example `pip install flake8`.
Alternatively, you can configure the settings in the IDE you use, for example VsCode, to automatically lint the code using flake8, the instructions for which I suggest you google.

I look forward to your contribution.

**Comment by X0rD3v1L** [comment]
Thanks! Updated it.

**Review by codeperfectplus — APPROVED** [review]
Thanks for contributing to the repository. Looking more contribution in future.
---
Join Py-Contributors Community 
[Discord](https://discord.gg/FXyh2S3)  • [Telegram](https://t.me/pycontributors)  • [website](https://py-contributors.github.io/)
---
Please share your Hacktober Experience on [Discord Channel](https://discord.gg/FXyh2S3) to Encourage more member to contribute to open source.
Happy Coding

**Pull request merged**
