### PR TITLE
Added Binary search program of cpp.(Bonus:I added code for linear search too)

### PR DESCRIPTION
**Pull request by coder-023**
### Self Check(Tick After Making pull Request)

- [ ] One Change in one Pull Request
- [ ] This issue was assigned to me
- [x] My file is in proper folder
- [x] I am following clean code and Documentation.
- [x] I have added title and what program will do first in the file

example:
```python
"""
Title - Bubble sort Algorithm
It will sort array
time complexity - 
"""
```

Become a maintainer on this repo - https://discord.gg/D4YmRxY

### CODE REVIEW

**Comment by SSKale1** [comment]
This issue has not been assigned to you. We'll have to close this.

**Comment by coder-023** [comment]
Really Sorry. Being a beginner in open sourcing, I wasn't aware of this that its assigned based task. I don't have a problem with the closing but  its a request to please remove the invalid tag.

**Comment by SSKale1** [comment]
All of these are assignment based tasks, and make sure you read the contributing guidelines for any repo that you would contribute in the future. As for now we'll have to abide by our guidelines for tags, no hard feelings.

**Comment by coder-023** [comment]
I understand your position.  I learned something out of this. Thank you! And I will definitely read and follow the guidelines from now!

**Comment by SSKale1** [comment]
@coder-023 That is exactly what hacktoberfest is for to give people an introduction to Open Source.

**Pull request closed without merging**
