### PR TITLE
Added code for the maximum pairwise product problem

### LINKED ISSUE #623: Maximum Pairwise Product | Algorithms | C++
## **`Maximum Pairwise Product`** -

**What will change** -
Add code for the Maximum Pairwise Product problem, in C++.

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

### PR DESCRIPTION
**Pull request by shrey27tri01**
### What have you Changed -

Added code for the Maximum Pairwise Product problem in C++.

### Issue no. - #

Issue #623 

### Self Check -

- [x] This issue was assigned to me if not it will marked as spam.
- [x] My file is in proper folder
- [x] I am following clean code and Documentation.My code is well linted and I am using flake8 standard for python
- [x] I have added title and what program will do first in the file

### README - [How to Contribute](https://github.com/Py-Contributors/AlgorithmsAndDataStructure/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by codeperfectplus** [comment]
Thanks for contributing to the repository. Looking more contribution in future.
---
Join Py-Contributors Community 
[Discord](https://discord.gg/FXyh2S3)  • [Telegram](https://t.me/pycontributors)  • [website](https://py-contributors.github.io/)
---
Please share your Hacktober Experience on [Discord Channel](https://discord.gg/FXyh2S3) to Encourage more member to contribute to open source.
Happy Coding

**Comment by shrey27tri01** [comment]
Hey @codePerfectPlus , sorry if I may sound a bit annoying here, but can you please approve or merge this PR, or tag it as `hacktoberfest-accepted`? :sweat_smile: 
Or suggest further changes, if necessary?

**Comment by shubham5351** [comment]
@shrey27tri01 can you add it in proper folder if I'm right it is not searching problem after this I will merge your code.

**Comment by shrey27tri01** [comment]
@shubham5351 Sure! Um, I am not so sure about which other folder to put this code in. Can you please help me out here? 
Or, I think that a new folder be created for `Other Algorithms`, for those contributors who are not sure about where to put their algorithm or data structure. :)

**Comment by shrey27tri01** [comment]
@shubham5351 I have created a new directory 'Maths' and added my code there. Please review the changes.

**Comment by shubham5351** [comment]
@shrey27tri01 Thanks for contributing.

**Pull request merged**
