### PR TITLE
Solve minimum cost path

### LINKED ISSUE #681: Minimum cost path | Dynamic programming | C++
## **`Title`** -

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [ ] Improving Code
- [ ] Improving Documentation
- [ ] Bug Fix

### Programming Language

Please add/delete options that are not relevant.

- [ ] Python
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

### PR DESCRIPTION
**Pull request by gowry189**
### What have you Changed(must)
Coded minimum path cost for a matrix traversal from (0,0) to (n-1,n-1)
followed by tracing the path of the minimum cost
### Issue no.(must) - #681

Pr will be closed and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [+] This issue was assigned to me if not it will marked as spam.
- [+] My file is in proper folder
- [+] I am following clean code and Documentation.My code is well linted and I am using flake8 standard for python
- [+] I have added title and what program will do first in the file

### CODE REVIEW

**Comment by codeperfectplus** [comment]
issue no. is not correct
#678 is Pull Request number, not an issue number.

**Comment by gowry189** [comment]
wasn't working on any issue. I was proposing a new feature.

**Comment by codeperfectplus** [comment]
yes, we have clear guidelines for that, if you want to improve/add/delete any code. first, you have to create an issue. It helps our team to track the change in code and spam PR during Hacktober.

**Comment by gowry189** [comment]
issue no: #681

**Pull request merged**
