### PR TITLE
Adding K_Nearest_Neighbour.py

### PR DESCRIPTION
**Pull request by Halix267**
### Self Check(Tick After Making pull Request)

- [x] One Change in one Pull Request
- [x] This issue was assigned to me
- [x] My file is in proper folder
- [x] I am following clean code and Documentation.
- [x] I have added title and what program will do first in the file

example:
```python
"""
Title - K-nearest_neighbour_algorithm

"""
```

Become a maintainer on this repo - https://discord.gg/D4YmRxY

### CODE REVIEW

**Comment by Halix267** [comment]
Hey @codePerfectPlus  . I have added the changes .Plzz review it

**Comment by codeperfectplus** [comment]
@Halix267 Issue no. is missing for reviewing

**Comment by Halix267** [comment]
Actually i new to open source so can u guide me what additional things i need to add. 
Thank u :)

**Comment by codeperfectplus** [comment]
Create an issue about what you want to change is codebase and assigned to the task. It helps us to track changes in the repository

**Comment by Halix267** [comment]
I have added issue no and what i have change in codebase @codePerfectPlus .Plzz review it if this is ok

**Review by hot9cups — COMMENTED** [review]
We have added a linter to the repo. This helps to keep the code organised.

Please fetch the latest version of the repo and resubmit. 
Make sure your code is linted with flake8 otherwise we won't be able to acccept the PR.
Good luck.

**Pull request closed without merging**
