### PR TITLE
Subset Sum

### LINKED ISSUE #35: Subset sum | Backtracking | Python
Please fill all details for a better explanation of the issue. Add files to the proper folder. Ask for Assigned before making PR.

**Title** -  Subset sum problem is the problem of finding a subset such that the sum of elements equal a given number. The backtracking approach generates all permutations in the worst case but in general, performs better than the recursive approach towards subset sum problem.

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

**Note** - One Change in one Pull Request

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

### PR DESCRIPTION
**Pull request by HimadriPathak**
### What have you Changed(must) -  I have added a new file Sumset_sum.py and the path is - AlgorithmsAndDataStructure\Python\Algorithms\DynamicPrograming
it takes no. of array element then the element one at a time then the sum you want as an input and gives you the output if a subset exist or not with the sum and set provided 

if their is any issue regarding the pr and coding plz inform

Write here what you have changed in cosebase

### Issue no.(must) - #35 

Pr will be close and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me if not it will marked as spam.
- [x] My file is in proper folder
- [x] I am following clean code and Documentation.My code is well linted and I am using flake8 standard for python
- [x] I have added title and what program will do first in the file

### CODE REVIEW

**Comment by HimadriPathak** [comment]
@hot9cups
plz check my code

**Review by hot9cups — CHANGES_REQUESTED** [review]
Please also print the subset if a subset is found, right now it only prints whether or not the subset exists.
Secondly, the code fails on an input like this:
A list of 5 elements [1,2,3,4,5] and target sum is 4.
The program outputs no such subset found.
(The same is true even if the target sum was 1 or 2 or 3. It appears to be working for 5 though).

Please fix the bug.

**Review by codeperfectplus — APPROVED** [review]

**Comment by codeperfectplus** [comment]
ignore the above line.

**Comment by HimadriPathak** [comment]
@codePerfectPlus and @hot9cups 
so is it going to merge or do I have to do the changes, if you want that changes it will be like the recursive one

**Comment by hot9cups** [comment]
Ofcourse you're required to make the changes. The current code provides wrong output for certain cases, which I've mentioned earlier, as well as doesn't actually print the subset. It's incorrect and incomplete.

**Comment by HimadriPathak** [comment]
@hot9cups 
I have done all the changes you wanted so please check

**Review by hot9cups — APPROVED** [review]
This is good, well-written code. Thank you for your contribution

**Pull request merged**
