### PR TITLE
 Solved Integer to Roman

### LINKED ISSUE #808: Roman and Integer
## **` Roman and Integer `** 

** I Can add a Def in the RomanToInt.py file for Integer to Roman ** 

can I work on this code and build my idea?

### PR DESCRIPTION
**Pull request by Techkrish1**
**Integer to Roman**

Issue No. #808 
I added a program for converting Integer to Roman.

1. [ ] It is super fast as you mentioned.
2. [ ] converting Integer to Roman

Please check this code and accept my pull request.
Thank you

### CODE REVIEW

**Comment by Techkrish1** [comment]
Please review my request and approve my workflow.

**Review by codeperfectplus — APPROVED** [review]
Thanks for contributing.

**Comment by codeperfectplus** [comment]
Please change, code according to the flake8 guide.

**Comment by Techkrish1** [comment]
please assign me issue808. I will fix this.

**Pull request closed without merging**
