### PR TITLE
Doubly LinkedList Added

### PR DESCRIPTION
**Pull request by kshitij9896**
### Self Check(Tick After Making pull Request)

- [x] One Change in one Pull Request
- [ ] This issue was assigned to me
- [x] My file is in proper folder
- [x] I am following clean code and Documentation.
- [x] I have added title and what program will do first in the file

example:
```python
"""
Title - Bubble sort Algorithm
It will sort array
time complexity - 
"""
```

### CODE REVIEW

**Review by SSKale1 — COMMENTED** [review]
Remove the extra line numbers 197-235

**Comment by SSKale1** [comment]
Please mention the Issue numbers and fill in the tick boxes. And only then do make commits.

**Comment by kshitij9896** [comment]
Doubly LinkedList Added 
Doubly LinkedList New Programme Added
Issue #290

**Comment by hot9cups** [comment]
There is no corresponding issue for this. You can only work on issues assigned to you

**Pull request closed without merging**
