### PR TITLE
Added hamiltonian Cycle program

### PR DESCRIPTION
**Pull request by harshitgupta2000**
## Pull Request Template

###New program

Write here what you have changed in cosebase

#586 .(must) - #

Pr will be close and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [ ] This issue was assigned to me if not it will marked as spam.
- [x] My file is in proper folder
- [x] I am following clean code and Documentation.My code is well linted and I am using flake8 standard for python
- [x] I have added title and what program will do first in the file

### CODE REVIEW

**Comment by SSKale1** [comment]
Please create PR only after you have been assigned the issue. We'll be closing this PR Now.

**Comment by harshitgupta2000** [comment]
Why you have done this i contributed with a good intention but i think the admin is arrogant it's ok there are many good repo.

**Comment by SSKale1** [comment]
You have to follow the contribution guidelines, and make a PR only when you have been assigned to the issue. It helps us keep track of the issues and prevent conflicts in the codebase as the issue may already be assigned to someone else.

**Comment by SSKale1** [comment]
@harshitgupta2000 Intentions may be good but it was a duplicate issue after all. Also for further contributions to any other Repos, make sure that you read their contribution guidelines before making any issue or PR.

**Pull request closed without merging**
