### PR TITLE
Added N Queens 2 problem for Backtracking concept in Cpp.

### PR DESCRIPTION
**Pull request by diva-21**
`Please fill all the details and checkbox, so we can merge PR faster.`

### What have you Changed(must)

I have added a new problem "N queens 2 " which is quite asked in backtracking concepts and in interviews. Probably most of  them will do the lenghty way (copying the same from N queens 1)  but i have written in an efficient and with full comments.
The code will be self explainatory and modified the way of looking Backtracking algorithm .

### Issue no.(must) - #881 

Pr will be closed and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [ ] This issue was assigned to me if not it will marked as spam.
- [x] My file is in proper folder
- [ ] I am following clean code and Documentation.My code is well linted and I am using flake8 standard for python
- [x] I have added title and what program will do first in the file

## acknowledgment
- [x] I have tested the script and distributed it under an MIT license.

### CODE REVIEW

**Comment by aayushi-droid** [comment]
@codePerfectPlus Duplicate PR, NQueen is already implemented.

**Comment by diva-21** [comment]
Also added another problem on BFS

**Comment by diva-21** [comment]
> @codePerfectPlus Duplicate PR, NQueen is already implemented.

but this type is not there , i made number of ways to place queens in a cp manner

**Comment by diva-21** [comment]
okay, can u review bfs problem

**Review by aayushi-droid — APPROVED** [review]

**Comment by codeperfectplus** [comment]
Thanks for making your contributions.

you can join us on telegram for more updates about Hacktoberfest.

Join Hacktoberfest Community Channels/Server.

- Raise an [Issue to join the organization(self invite)](https://github.com/Py-Contributors/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invite.yaml&title=Please+invite+me+to+the+GitHub+Community+Organization)

 - [Telegram](https://t.me/hacktober2022)
 - [Discord](https://discord.gg/JfbK3bS)

Happy hacktoberfest

**Pull request merged**
