### PR TITLE
added topological sorting

### LINKED ISSUE #220: Topological Sorting | Graph| C++
## **`Topological Sorting`** 

**what will change** -

### Type of Issue -
- [x] Adding New Code

### Programming Language
- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

### PR DESCRIPTION
**Pull request by Shagunjain10**
### Topological Sorting | Graph| C++
Added Topological Sorting

### Issue no.(must) - #220 

Pr will be close and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [ ] This issue was assigned to me if not it will marked as spam.
- [ ] My file is in proper folder
- [ ] I am following clean code and Documentation.My code is well linted and I am using flake8 standard for python
- [ ] I have added title and what program will do first in the file

### CODE REVIEW

**Comment by shubham5351** [comment]
@Shagunjain10 please see the code it is not giving the expected output can you please verify it once again, and also if possible make it user friendly and add proper comments in it with title at the top.

**Comment by Shagunjain10** [comment]
Okay, I will do it soon.

**Comment by Shagunjain10** [comment]
Can you please share the test case where this code is given unexpected output. My code is based on 1-based Indexing.  On my test cases this given expected output.
sample test case Input
5 6
1 2
1 3
2 3
2 4
3 4
3 5
Sample output
1 2 3 4 5

**Comment by shubham5351** [comment]
So this is the test case:-
Sample input case :- 
5 2
5 0
4 0
4 1
2 3
3 1
Sample Output :- 
5 4 2 3 1 0

Please comment the code properly with title at the top and if possible make it user friendly.

**Comment by Shagunjain10** [comment]
In the first line of sample code, you specify 5 nodes and 2 edges but in the next five lines, you specify the edges. That's why this code not giving the expected output. Also, the sample output contains 6 nodes.

**Comment by shubham5351** [comment]
It are only the edges I specified in the above sample input and I have also given 6edges and 6nodes input can you please verify it once more.

**Comment by Shagunjain10** [comment]
I updated the code from 1-based indexing to 0-based indexing also added the comments to make user-friendly code.
On sample input test case:- 
6 6
5 2
5 0
4 0
4 1
2 3
3 1
It gives the output:-
Topological Sorting of this Graph is : 4 5 2 0 3 1
which is correct.
Please review this code.

**Comment by shubham5351** [comment]
@Shagunjain10 can you verify it once more as 1 and 0 should be present at last beacause its indegree is 2, and 3 should be before them.After that I will merge your code.

**Comment by Shagunjain10** [comment]
Yes, Initially 1 and 0 have indegree 2. 0 have indegree 2 because of 4 and 5 nodes, and after 4 and 5 added in topological sorting, then the indegree of 0 becomes 0 because of which 0 added before 3. But this is not the case with 1, 1 have indegree 2 because of 4 and 3 nodes.  So 1 added after 3.

**Review by hot9cups — APPROVED** [review]
So let's look at the graph for the input that was provided.

image

The output that we received was 4 5 2 0 3 1

According to the graph we have above, let's verify if the sort is correct.
4 has edges towards 0 and 1, in the output 0 and 1 both are after 4.
5 has an edge towards 2, in the output 2 is after 5.
2 has an edge towards 3, in the output 3 is after 2.
0 has no outgoing edges. So no constraints.
3 has an edge towards 1, in the output 1 is indeed after 3.
1 has no outgoing edges, so again no constrains.

Hence the toplogical sort indeed is valid. There could be multiple topological sorts for a graph, like here 2 more sorts could be:
5 4 2 3 1 0 as well as 4 5 2 3 1 0 (which @shubham5351 mentioned). Either of them is fine.

You may go ahead and merge this Shubham, if you're happy with the code style and everything else.

**Review by shubham5351 — APPROVED** [review]

**Pull request merged**
