### PR TITLE
Proofreading and copyediting changes made.

### PR DESCRIPTION
**Pull request by danschenker**
### What have you Changed(must)

I made a handful of grammatical and spelling changes throughout the README file

### Issue no.(must) - #880

Pr will be closed and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me if not it will marked as spam. (I am making the first sweep of changes. This issue is also assigned to @jeslyw)
- [x] My file is in proper folder
- [x] I am following clean code and Documentation.My code is well linted and I am using flake8 standard for python
- [x] I have added title and what program will do first in the file

## acknowledgment
- [x] I have tested the script and distributed it under an MIT license.

### CODE REVIEW

**Review by codeperfectplus — APPROVED** [review]
Thanks for making your contributions. It's a really amazing contribution.

you can join us on telegram for more updates about Hacktoberfest.
Hacktoberfest Channel:- t.me/hacktober2022

Happy hacktoberfest

**Comment by danschenker** [comment]
> Thanks for making your contributions. It's a really amazing contribution.
> 
> you can join us on telegram for more updates about Hacktoberfest. Hacktoberfest Channel:- t.me/hacktober2022
> 
> Happy hacktoberfest

Glad I could help! Just as a heads up, it looks like Hacktoberfest is excluding contributions to this repo:
>Your PR/MR was submitted to a repository that has been excluded from Hacktoberfest as it does not follow the values of the event. It will not count towards your participation.

**Comment by codeperfectplus** [comment]
> > Thanks for making your contributions. It's a really amazing contribution.
> > you can join us on telegram for more updates about Hacktoberfest. Hacktoberfest Channel:- t.me/hacktober2022
> > Happy hacktoberfest
> 
> Glad I could help! Just as a heads up, it looks like Hacktoberfest is excluding contributions to this repo:
> 
> > Your PR/MR was submitted to a repository that has been excluded from Hacktoberfest as it does not follow the values of the event. It will not count towards your participation.

For the last 2 years, It was included in the Hacktoberfest event. It looks like they have changed some criteria. I just checked

**Comment by danschenker** [comment]
Yeah, it looks like they made some changes this year. Figured you'd want to know!

**Comment by codeperfectplus** [comment]
They are excluding the repo for Algorithm and Data structure this repo.

> Yeah, it looks like they made some changes this year. Figured you'd want to know!

**Comment by codeperfectplus** [comment]
AlgorithmsAndDataStructure repo is excluded. The hacktoberfest team is removing the DSA repository.
There is one more repo you can contribute. Please check the below link.

`https://github.com/codePerfectPlus/awesomeScripts`
Currently, It's included in Hacktoberfest.

@danschenker

**Pull request merged**
