### PR TITLE
cycle in an undirected graph added

### PR DESCRIPTION
**Pull request by mukundkedia**
### Self Check(Tick After Making pull Request)

- [x] One Change in one Pull Request
- [x] This issue was assigned to me
- [x] My file is in proper folder
- [x] I am following clean code and Documentation.
- [x] I have added title and what program will do first in the file

Title - Cycle in an undirected graph
It will find whether cycle is present in an undirected graph or not
time complexity - O(V+E)

Become a maintainer on this repo - https://discord.gg/D4YmRxY

### CODE REVIEW

**Review by SSKale1 — CHANGES_REQUESTED** [review]
Please add comments at the beginning of the code. Describing the code and Time/Space Complexities if applicable.

**Review by SSKale1 — CHANGES_REQUESTED** [review]
Add Comments to the start of code explaining the program. Time/space complexities if applicable.

**Comment by hot9cups** [comment]
Marking invalid, will close in 2 days if there's no response.

**Comment by mukundkedia** [comment]
will make necessary changes within a day.

**Comment by hot9cups** [comment]
@mukundkedia I will close this today if there is no activity here

**Comment by codeperfectplus** [comment]
Closing the PR
- No changes

**Pull request closed without merging**
