### PR TITLE
Wiggle Sort | Sorting Algorithms | Python

### LINKED ISSUE #662: Wiggle Sort | Sorting | Python
## **`Title`** - Wiggle Sort | Sorting Algorithm | Python

**what will change** - Implementation of wiggle sort algorithm

### Type of Issue -

- [x] Adding New Code

### Programming Language

- [x] Python

### Self Check 

- 

- [x]  Ask for issue assignment before making Pull Request.
- [x] Add your file in the proper folder
- [x]  `Clean Code` and `Documentation` for better readability
- [x] Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

### PR DESCRIPTION
**Pull request by Kamesh-Mishra**
### What have you Changed(must)

Added Wiggle Sort

### Issue no.(must) - #662

Pr will be closed and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me if not it will marked as spam.
- [x] My file is in proper folder
- [x] I am following clean code and Documentation.My code is well linted and I am using flake8 standard for python
- [x] I have added title and what program will do first in the file

### CODE REVIEW

**Comment by Kamesh-Mishra** [comment]
@codePerfectPlus can you please help me to solve this issue.

**Comment by codeperfectplus** [comment]
go through Flake8 documentation for code linting.- https://flake8.pycqa.org/en/latest/

**Comment by Kamesh-Mishra** [comment]
@codePerfectPlus done.

**Review by codeperfectplus — APPROVED** [review]
Thanks for contributing to the repository. Looking more contribution in future.
---
Join Py-Contributors Community 
[Discord](https://discord.gg/FXyh2S3)  • [Telegram](https://t.me/pycontributors)  • [website](https://py-contributors.github.io/)
---
Please share your Hacktober Experience on [Discord Channel](https://discord.gg/FXyh2S3) to Encourage more member to contribute to open source.
Happy Coding

**Pull request merged**
