### PR TITLE
I added an imp application of DSU, No of Provinces

### PR DESCRIPTION
**Pull request by diva-21**
`Please fill all the details and checkbox, so we can merge PR faster.`

### What have you Changed(must)
An important application of DSU, i.e number of clusters in a graph is efficiently with Disjoint Set Union algorithm.
And DSU is quite useful in other algos like Krushkal and Prims.

### Issue no.(must) - #613 

Pr will be closed and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [ ] This issue was assigned to me if not it will marked as spam.
- [x] My file is in proper folder
- [x] I am following clean code and Documentation.My code is well linted and I am using flake8 standard for python
- [x] I have added title and what program will do first in the file

## acknowledgment
- [x] I have tested the script and distributed it under an MIT license.

### CODE REVIEW

**Comment by diva-21** [comment]
Quick sort added in java algorithms , please review it @codePerfectPlus

**Comment by diva-21** [comment]
Morris Traversal in trees added @codePerfectPlus . PLease review it sir

**Review by aayushi-droid — APPROVED** [review]

**Comment by diva-21** [comment]
vertical traversal on trees added which is a hard question, please review it

**Comment by codeperfectplus** [comment]
Thanks for reviewing @aayushi-droid , Thanks @diva-21 for your contribution.

**Comment by diva-21** [comment]
> Thanks for reviewing @aayushi-droid , Thanks @diva-21 for your contribution.

Wishing to add more contributions @codePerfectPlus sir

**Pull request merged**
