### PR TITLE
Added Tim Sort Algorithm

### PR DESCRIPTION
**Pull request by soum-sr**
### What have you Changed(must)

I have added a new file ```TimSort.py``` at ```Python/Algorithms/SortimgAlgorithms```.

### Issue no.(must) - #654 

Pr will be closed and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me if not it will marked as spam.
- [x] My file is in proper folder
- [x] I am following clean code and Documentation.My code is well linted and I am using flake8 standard for python
- [x] I have added title and what program will do first in the file

### CODE REVIEW

**Review by hot9cups — CHANGES_REQUESTED** [review]
Could you add provision for user input - for the array?

**Comment by soum-sr** [comment]
I've updated code and given provision for user input, for the array

**Review by hot9cups — APPROVED** [review]
Perfect. 
Well-written, neat code.
Thank you for your contribution.

**Comment by soum-sr** [comment]
Thank you very much!

**Pull request merged**
