### PR TITLE
Russian Peasant Algorithm

### PR DESCRIPTION
**Pull request by mahimagoyalx**
### Self Check(Tick After Making pull Request)

- [x] One Change in one Pull Request
- [x] This issue was assigned to me
- [x] My file is in proper folder
- [x] I am following clean code and Documentation.
- [x] I have added title and what program will do first in the file

example:
```python
"""
Title - Bubble sort Algorithm
It will sort array
time complexity - 
"""
```

### CODE REVIEW

**Comment by shubham5351** [comment]
@mahimagoyalx the code is running perfect but if the 2nd number is negative it is not giving proper output if possible can you work on it, Then I will merge your code.

**Comment by mahimagoyalx** [comment]
> @mahimagoyalx the code is running perfect but if the 2nd number is negative it is not giving proper output if possible can you work on it, Then I will merge your code.

Yes, sure, I will make the changes.

**Comment by hot9cups** [comment]
Marking invalid, will close if there is no response within 2 days.

**Review by hot9cups — COMMENTED** [review]
Closing due to inactivity

**Pull request closed without merging**
