### PR TITLE
Add trie Data Structure in c++

### LINKED ISSUE #883: Trie Data Structure | Data Structure | C++
## **`Title`** -
Add Trie Data Structure in C++
**what will change** -
Trie Data Structure will be added to the c++ DS folder, currently missing
### Type of Issue -
Addition of new Data Structure
Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

### PR DESCRIPTION
**Pull request by adityaajay29**
`Please fill all the details and checkbox, so we can merge PR faster.`

### What have you Changed(must)

Added implementation of trie data structure in c++ along with example problems.
The code is well structured and commented.
I tried to make a PR 11 days ago as well but I couldn't create one at that time.

### Issue no.(must) - #883 

Pr will be closed and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me if not it will marked as spam.
- [x] My file is in proper folder
- [x] I am following clean code and Documentation.My code is well linted and I am using flake8 standard for python
- [x] I have added title and what program will do first in the file

## acknowledgment
- [x] I have tested the script and distributed it under an MIT license.

### CODE REVIEW

**Review by codeperfectplus — COMMENTED** [review]
Please do the below changes.

1. Remove .DS_Store files.
2. add proper naming to your file. _1implement.cpp is confusing.

Thanks

**Comment by adityaajay29** [comment]
Thanks for the review. I have made the necessary changes. Please review this.

**Review by aayushi-droid — APPROVED** [review]
Looks fine to me.

**Comment by codeperfectplus** [comment]
Thanks, @aayushi-droid  for reviewing the code.

**Review by codeperfectplus — APPROVED** [review]
Thanks for making your contributions.

you can join us on telegram for more updates about Hacktoberfest.

Join Hacktoberfest Community Channels/Server.

- Raise an [Issue to join the organization(self invite)](https://github.com/Py-Contributors/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invite.yaml&title=Please+invite+me+to+the+GitHub+Community+Organization)

 - [Telegram](https://t.me/hacktober2022)
 - [Discord](https://discord.gg/JfbK3bS)

Happy hacktoberfest

**Comment by adityaajay29** [comment]
> Thanks for making your contributions.
> 
> you can join us on telegram for more updates about Hacktoberfest.
> 
> Join Hacktoberfest Community Channels/Server.
> 
> * Raise an [Issue to join the organization(self invite)](https://github.com/Py-Contributors/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invite.yaml&title=Please+invite+me+to+the+GitHub+Community+Organization)
> * [Telegram](https://t.me/hacktober2022)
> * [Discord](https://discord.gg/JfbK3bS)
> 
> Happy hacktoberfest

Sure!
Thanks a lot :)

**Pull request merged**
