### PR TITLE
Create Karatsuba_Algorithm

### LINKED ISSUE #444: KARATSUBA | Divide And Conquer | C++
## **`KARATSUBA ALGORITHM`** -

**Adding new Code** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

### PR DESCRIPTION
**Pull request by KISLAYA-SRI**
### What have you Changed(must)

Write here what you have changed in codebase

### Issue no.(must) - #

Pr will be closed and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me if not it will marked as spam.
- [x] My file is in proper folder
- [ ] I am following clean code and Documentation.My code is well linted and I am using flake8 standard for python
- [x] I have added title and what program will do first in the file

### CODE REVIEW

**Comment by codeperfectplus** [comment]
issue number #444 
you should mention the issue number in the template. next time it will be marked as spam.

**Comment by codeperfectplus** [comment]
Code-format is wrong. there is no extension in your file.
example. algorithm.cc, algorithm.cpp

**Comment by codeperfectplus** [comment]
No Response,  closing the PR

**Comment by KISLAYA-SRI** [comment]
Sorry, I wasn't active...again creating PR with correct format...

**Pull request closed without merging**
