### PR TITLE
Added the C++ Code

### PR DESCRIPTION
**Pull request by Sandesh1013**
### Self Check(Tick After Making pull Request)

- [x] One Change in one Pull Request
- [x] This issue was assigned to me
- [x] My file is in proper folder
- [x] I am following clean code and Documentation.
- [x] I have added title and what program will do first in the file

example:
```C++
"""
Title -Count Inversion
It will sort count number of inversions of an n-length array
"""
```

Become a maintainer on this repo - https://discord.gg/D4YmRxY

### CODE REVIEW

**Review by SSKale1 — CHANGES_REQUESTED** [review]
Please add comments at the beginning of the code, explaining the program, and comments for better readability.

**Comment by Sandesh1013** [comment]
Okay sure, I'll add the comments.

**Comment by hot9cups** [comment]
Marking Invalid, will close if there is no response in the next 2 days.

**Review by hot9cups — COMMENTED** [review]
Closing due to inactivity

**Pull request closed without merging**
