### PR TITLE
Create Fibonacci.cpp

### PR DESCRIPTION
**Pull request by Ankit-11-Code**
### Self Check(Tick After Making pull Request)

- [ ] One Change in one Pull Request
- [ ] This issue was assigned to me
- [x] My file is in proper folder
- [x] I am following clean code and Documentation.
- [ ] I have added title and what program will do first in the file

example:
```python
"""
Title - Bubble sort Algorithm
It will sort array
time complexity - 
"""
```

Become a maintainer on this repo - https://discord.gg/D4YmRxY

### CODE REVIEW

**Comment by shubham5351** [comment]
@Ankit-11-Code please fill the pull request template and in fibonacci program please add the title on the top and add test cases at the bottom After this i will review it asap.

**Comment by sherwin2000** [comment]
please will u assign me this issue?

**Comment by Ankit-11-Code** [comment]
> @Ankit-11-Code please fill the pull request template and in fibonacci program please add the title on the top and add test cases at the bottom After this i will review it asap.

Ok

**Comment by sherwin2000** [comment]
please assign it to me

**Comment by shubham5351** [comment]
duplicate issue no - #85

**Pull request closed without merging**
