### PR TITLE
Added Palindrome Partitioning in cpp

### LINKED ISSUE #315: Palindrome Partitioning | Dynamic Programming | C++
## **Palindrome Partitioning** -

**We can solve the problem of palindrome partitioning by Dynamic Programming** 

### Type of Issue - Dynamic Programming

- [x] Adding New Code

### Programming Language

- [x] C++

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

### PR DESCRIPTION
**Pull request by deekshalala**
### What have you Changed(must)

Added Palindrome Partitioning in Cpp 

### Self Check(Tick After Making pull Request)

- [ ] This issue was assigned to me if not it will marked as spam.
- [ ] My file is in proper folder
- [ ] I am following clean code and Documentation.My code is well linted and I am using flake8 standard for python
- [ ] I have added title and what program will do first in the file

### CODE REVIEW

**Comment by shubham5351** [comment]
@deekshalala I have checked your code it is running perfectly but can you please take the input from user, Then I will merge your code.

**Comment by deekshalala** [comment]
@shubham5351 Sure!

**Comment by shubham5351** [comment]
@deekshalala can you please test this string(aabaaaabaa) it is giving wrong output.

**Comment by deekshalala** [comment]
Sir,
The string is palindrome itself. Thus, the program gives 0 as answer as it
doesn't require partition to become a palindrome.

**Review by shubham5351 — APPROVED** [review]

**Comment by shubham5351** [comment]
Ok sorry for the trouble I will merge it.

**Pull request merged**
