### PR TITLE
Interpolation Search and Documentation 

### LINKED ISSUE #543: Interpolation Search | Searching Algorithms | Python
## Interpolation Search -

Given a sorted array of n uniformly distributed values arr[], write a function to search for a particular element x in the array.
Thus, Interpolation search will be added in Python->Algorithms->Searching Algorithms .

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code
- [x] Improving Documentation

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

### PR DESCRIPTION
**Pull request by xma8lu**
### What have you Changed(must)

Added InterpolationSearch.py to Python Searching Algorithms &
Written a completely NEW and clean Readme.md file in Python Searching Algorithms
### Issue no.(must) - #543 

Pr will be close and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [ ] This issue was assigned to me if not it will marked as spam.
- [ ] My file is in proper folder
- [ ] I am following clean code and Documentation.My code is well linted and I am using flake8 standard for python
- [ ] I have added title and what program will do first in the file

### CODE REVIEW

**Review by hot9cups — CHANGES_REQUESTED** [review]
The code and documentation is good. 
However, the input array `arr` and the pivot `x` are hardcoded. I would like this to be taken from the user as input. Please make the required changes and I'll be happy to merge the PR.

**Comment by xma8lu** [comment]
Hey I have made the necessary changes and clicked on the pull request 
But am confused do I have to open a new pull request by closing this one or will the changes be reflected here itself

**Comment by xma8lu** [comment]
@hot9cups

**Review by codeperfectplus — APPROVED** [review]
Thanks for contributing to the repository. Looking more contribution in future.
---
Join Py-Contributors Community 
[Discord](https://discord.gg/FXyh2S3)  • [Telegram](https://t.me/pycontributors)  • [website](https://py-contributors.github.io/)
---
Please leave a star(:star:) on other repo too.
Happy Coding

**Comment by codeperfectplus** [comment]
Thanks for the documentation too

**Pull request merged**
