### PR TITLE
Create Integer/Binary Code to Gray Code Conversion

### LINKED ISSUE #400: Binary to Gray Code Conversion | Algebra/Number_System | Python
## **`Binary to Gray Code Conversion`** -

**what will change** -

### Type of Issue -

Please add/delete options that are not relevant.

- [x] Adding New Code

### Programming Language

Please add/delete options that are not relevant.

- [x] Python

### Self Check 

- Ask for issue assignment before making Pull Request.
- Add your file in the proper folder
- `Clean Code` and `Documentation` for better readability
- Add `Title` and `Description` of the program in the file

:star2: Star it :fork_and_knife:Fork it :handshake: Contribute to it!

Discord server ✉️ - https://discord.gg/FXyh2S3

Happy Coding,

### PR DESCRIPTION
**Pull request by utsavk28**
### What have you Changed(must)

Added new binary to gray code conversion in algorithm/math

### Issue no.(must) - #400 

Pr will be close and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me if not it will marked as spam.
- [x] My file is in proper folder
- [x] I am following clean code and Documentation.My code is well linted and I am using flake8 standard for python
- [x] I have added title and what program will do first in the file

### CODE REVIEW

**Review by codeperfectplus — APPROVED** [review]
You upload code with .py extension. Check your code for Python Linting

**Review by hot9cups — CHANGES_REQUESTED** [review]
This is supposed to be a Binary code to Gray code conversion.
What you're doing is taking a base 10 number, an integer, and converting it into binary and gray code.

Your input should be the binary code, not the integer.
Otherwise, provide the user the option to enter integer as well as binary code and convert based on what they entered.

**Comment by utsavk28** [comment]
Changes hve been made

**Review by hot9cups — APPROVED** [review]
Look good. Thank you for your contribution.

**Pull request merged**
