### PR TITLE
Linear Search 

### PR DESCRIPTION
**Pull request by Shivansahni**
`Please fill all the details and checkbox, so we can merge PR faster.`

### What have you Changed(must)

Write here what you have changed in codebase
I have added Linear Search Program in Searching / algorithms .
### Issue no.(must) - #

Pr will be closed and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [ ] This issue was assigned to me if not it will marked as spam.
- [x] My file is in proper folder
- [ ] I am following clean code and Documentation.My code is well linted and I am using flake8 standard for python
- [ ] I have added title and what program will do first in the file

## acknowledgment
- [x] I have tested the script and distributed it under an MIT license.

### CODE REVIEW

**Comment by Shivansahni** [comment]
Hi! I have added Linear Searching in a searching folder in Algorithms. Please accept my request.

**Comment by codeperfectplus** [comment]
@Shivansahni It's good practice to create an issue before PR.

**Review by harshit-paneri — APPROVED** [review]
All Test Case Pass 🙌

**Review by romiljain23 — APPROVED** [review]
Good...Keep Contributing

**Comment by codeperfectplus** [comment]
Thanks, @harshit-paneri @romiljain23 for reviewing the code.

**Pull request merged**
