### PR TITLE
Quick sort

### PR DESCRIPTION
**Pull request by altafshaikh**
### Self Check(Tick After Making pull Request)

- [x] One Change in one Pull Request
- [ ] This issue was assigned to me
- [x] My file is in proper folder
- [x] I am following clean code and Documentation.
- [x] I have added title and what program will do first in the file

example:
```python
"""
Title - Quick sort Algorithm
It will sort array
time complexity - 
"""
```

### CODE REVIEW

**Review by hot9cups — COMMENTED** [review]
We have added a linter to the repo. This helps to keep the code organised.

Make sure your code is linted with flake8 otherwise we won't be able to acccept the PR.
Also you need to mention the Issue number in the PR and are only allowed to work on issues assigned to you

**Comment by altafshaikh** [comment]
@codePerfectPlus can you check this issue https://github.com/Py-Contributors/AlgorithmsAndDataStructure/pull/398 it is labelled duplicate you can ignore this PR as it has mistakes and please verify the #398 and approved the PR and if aany changes are their then let me know

**Comment by codeperfectplus** [comment]
@altafshaikh Please go through the documentation once. We are merging PR based on issues to avoid spam, conflict PR. you haven't mentioned the issue number so it's hard to find the issue was assigned to you or someone else. 
If the issue was assigned to someone else merging your PR may create a merge conflict. So please follow the guidelines. Help us to stop Spam.

**Comment by altafshaikh** [comment]
> @altafshaikh Please go through the documentation once. We are merging PR based on issues to avoid spam, conflict PR. you haven't mentioned the issue number so it's hard to find the issue was assigned to you or someone else.
> If the issue was assigned to someone else merging your PR may create a merge conflict. So please follow the guidelines. Help us to stop Spam.

okay

**Pull request closed without merging**
