### PR TITLE
string subsequence using rec

### PR DESCRIPTION
**Pull request by MdAkdas**
### What have you Changed(must) - 
new program

### Self Check(Tick After Making pull Request)

- [x] One Change in one Pull Request
- [ ] This issue was assigned to me
- [x] My file is in proper folder
- [x] I am following clean code and Documentation.
- [x] I have added title and what program will do first in the file

example:
```python
"""
Title - Bubble sort Algorithm
It will sort array
time complexity - 
"""
```

### CODE REVIEW

**Comment by MdAkdas** [comment]
@ExpressHermes @codePerfectPlus what am i getting wrong here?

**Comment by ExpressHermes** [comment]
Lint your code with flake8 before committing. Install flake8 using pip.

**Comment by hot9cups** [comment]
@MdAkdas Your code seems fine. We had an internal problem, could you please resubmit a new PR with your code, it should work fine now. Sorry about the goof-up.

**Review by codeperfectplus — COMMENTED** [review]
Thanks for making you contribution

**Pull request closed without merging**
