### PR TITLE
Create ternarySearch.cpp

### PR DESCRIPTION
**Pull request by KaushalDevrari**
### What have you Changed(must)

Write here what you have changed in cosebase

### Issue no.(must) - #

Pr will be close and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [ ] This issue was assigned to me if not it will marked as spam.
- [x] My file is in proper folder
- [ ] I am following clean code and Documentation.My code is well linted and I am using flake8 standard for python
- [x] I have added title and what program will do first in the file

### CODE REVIEW

**Comment by KaushalDevrari** [comment]
Can you please label it with hacktoberfest.

**Comment by codeperfectplus** [comment]
@KaushalDevrari merged PR will be marked as Hacktober-accepted. don't worry

**Comment by KaushalDevrari** [comment]
but this isn't merged.

**Comment by codePerfectPlus** [comment]
you didn't mention the issue number, how will be track the issue

**Comment by codeperfectplus** [comment]
How will track the issue? Mention the issue number for the issue tracking either the pr will be marked as spam according to self-check rule no. 1. Reporting PR as spam may ban your fromHacktober. Check rules from Hacktober website.

Rule 1
- [ ] This issue was assigned to me if not it will be marked as spam.

**Pull request closed without merging**
