### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by mohammedshibinv**
### What have you Changed(must)
Jump Search implementation
added JumpSearch.py  in folder python / Algorithms / searchingAlgorthms

### Issue no.(must) -  #724 

Pr will be closed and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me if not it will marked as spam.
- [x] My file is in proper folder
- [x] I am following clean code and Documentation.My code is well linted and I am using flake8 standard for python
- [x] I have added title and what program will do first in the file

### CODE REVIEW

**Comment by mohammedshibinv** [comment]
can you please add the label "hactoberfest accepted" after you verifying this

**Review by hot9cups — CHANGES_REQUESTED** [review]
You assume that the user will always enter the numbers in a sorted order.
That might not always be true, so do sort the array before searching for the element.

Once you make the change, I'll be happy to merge the PR.

**Comment by mohammedshibinv** [comment]
I just update JumpSearch.py as per  @hot9cups  request.
If any changes needed, Plz let me know. 
Thank You

**Review by hot9cups — APPROVED** [review]
I modified the code to get rid of the extra array and the index search that was being performed at the end(thus defeating the entire purpose of jumpsearch).

Apart from that, code looks good. Thank you for your contribution

**Comment by mohammedshibinv** [comment]
Thank you for guiding me @hot9cups

**Comment by hot9cups** [comment]
Thank you for your contribution. I look forward to more such PRs from you :)

**Comment by purva-saxena** [comment]
can you assign this issue to me?
i wanna do this!

**Pull request merged**
